FROM node:8.1.0

WORKDIR /opt/recipes-log

COPY controller/ controller
COPY lib/ lib
COPY model/ model
COPY route/ route
COPY node_modules/ node_modules
COPY index.js .
COPY package.json .

CMD ["node", "./index.js"] 